
export interface Product {
  id: string;
  name: string;
  sellPrice: number;
  costPrice: number;
  onHand: number;
  forecast: number;
  category: string;
  status: 'in-stock' | 'low-stock' | 'out-of-stock';
  supplier: string;
  sku: string;
  lastUpdated: string;
}

export const initialProducts: Product[] = [
  {
    id: '1',
    name: 'Red Wine (Cabernet Sauvignon)',
    sellPrice: 24.99,
    costPrice: 12.50,
    onHand: 250,
    forecast: 300,
    category: 'Wine & Spirits',
    status: 'in-stock',
    supplier: 'Grand Vineyards Ltd.',
    sku: 'WN-RED-CS',
    lastUpdated: '2025-03-10'
  },
  {
    id: '2',
    name: 'White Wine (Chardonnay)',
    sellPrice: 19.50,
    costPrice: 9.25,
    onHand: 180,
    forecast: 250,
    category: 'Wine & Spirits',
    status: 'in-stock',
    supplier: 'Grand Vineyards Ltd.',
    sku: 'WN-WHT-CH',
    lastUpdated: '2025-03-08'
  },
  {
    id: '3',
    name: 'Designer Evening Dress (Black)',
    sellPrice: 129.99,
    costPrice: 65.75,
    onHand: 45,
    forecast: 100,
    category: 'Fashion',
    status: 'low-stock',
    supplier: 'Elite Fashion House',
    sku: 'DR-EVN-BLK',
    lastUpdated: '2025-03-12'
  },
  {
    id: '4',
    name: 'Cocktail Dress (Red)',
    sellPrice: 89.99,
    costPrice: 42.50,
    onHand: 0,
    forecast: 75,
    category: 'Fashion',
    status: 'out-of-stock',
    supplier: 'Elite Fashion House',
    sku: 'DR-CKT-RED',
    lastUpdated: '2025-03-11'
  },
  {
    id: '5',
    name: 'Diamond Pendant Necklace',
    sellPrice: 299.50,
    costPrice: 150.25,
    onHand: 25,
    forecast: 35,
    category: 'Jewelry',
    status: 'in-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-NKL-DIA',
    lastUpdated: '2025-03-09'
  },
  {
    id: '6',
    name: 'Gold Hoop Earrings',
    sellPrice: 145.99,
    costPrice: 72.75,
    onHand: 60,
    forecast: 80,
    category: 'Jewelry',
    status: 'in-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-EAR-GLD',
    lastUpdated: '2025-03-15'
  },
  {
    id: '7',
    name: 'Ceramic Dinner Set (6-piece)',
    sellPrice: 79.99,
    costPrice: 39.25,
    onHand: 120,
    forecast: 150,
    category: 'Home & Kitchen',
    status: 'in-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-DIN-CER',
    lastUpdated: '2025-03-18'
  },
  {
    id: '8',
    name: 'Luxury Bedding Set (Queen)',
    sellPrice: 189.75,
    costPrice: 95.50,
    onHand: 35,
    forecast: 60,
    category: 'Home & Kitchen',
    status: 'low-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-BED-LUX',
    lastUpdated: '2025-03-05'
  },
  {
    id: '9',
    name: 'Designer Heels (Black, Size 7)',
    sellPrice: 159.99,
    costPrice: 82.25,
    onHand: 40,
    forecast: 65,
    category: 'Shoes',
    status: 'in-stock',
    supplier: 'Footwear Fashions',
    sku: 'SH-HEL-BLK7',
    lastUpdated: '2025-03-07'
  },
  {
    id: '10',
    name: 'Leather Boots (Brown, Size 8)',
    sellPrice: 199.50,
    costPrice: 99.75,
    onHand: 28,
    forecast: 50,
    category: 'Shoes',
    status: 'in-stock',
    supplier: 'Footwear Fashions',
    sku: 'SH-BOT-BRN8',
    lastUpdated: '2025-03-09'
  },
  {
    id: '11',
    name: 'Sparkling Wine (Prosecco)',
    sellPrice: 27.99,
    costPrice: 14.50,
    onHand: 90,
    forecast: 150,
    category: 'Wine & Spirits',
    status: 'low-stock',
    supplier: 'Grand Vineyards Ltd.',
    sku: 'WN-SPK-PRO',
    lastUpdated: '2025-03-12'
  },
  {
    id: '12',
    name: 'Crystal Wine Glasses (Set of 4)',
    sellPrice: 69.99,
    costPrice: 35.50,
    onHand: 65,
    forecast: 100,
    category: 'Home & Kitchen',
    status: 'low-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-GLS-CRY',
    lastUpdated: '2025-03-14'
  },
  {
    id: '13',
    name: 'Silver Bangle Bracelet',
    sellPrice: 79.99,
    costPrice: 39.75,
    onHand: 50,
    forecast: 75,
    category: 'Jewelry',
    status: 'in-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-BRC-SLV',
    lastUpdated: '2025-03-16'
  },
  {
    id: '14',
    name: 'Summer Floral Dress',
    sellPrice: 59.99,
    costPrice: 29.25,
    onHand: 85,
    forecast: 120,
    category: 'Fashion',
    status: 'in-stock',
    supplier: 'Elite Fashion House',
    sku: 'DR-SUM-FLR',
    lastUpdated: '2025-03-10'
  },
  {
    id: '15',
    name: 'Leather Handbag (Designer)',
    sellPrice: 249.50,
    costPrice: 125.75,
    onHand: 0,
    forecast: 40,
    category: 'Fashion',
    status: 'out-of-stock',
    supplier: 'Elite Fashion House',
    sku: 'BG-LTH-DSG',
    lastUpdated: '2025-03-11'
  },
  {
    id: '16',
    name: 'Decorative Throw Pillows (Set of 2)',
    sellPrice: 45.50,
    costPrice: 22.25,
    onHand: 75,
    forecast: 100,
    category: 'Home & Kitchen',
    status: 'in-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-PIL-DEC',
    lastUpdated: '2025-03-08'
  },
  {
    id: '17',
    name: 'Rose Gold Watch (Ladies)',
    sellPrice: 175.99,
    costPrice: 87.50,
    onHand: 15,
    forecast: 30,
    category: 'Jewelry',
    status: 'low-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-WTC-RGF',
    lastUpdated: '2025-03-13'
  },
  {
    id: '18',
    name: 'Ballet Flats (Nude, Size 6)',
    sellPrice: 79.99,
    costPrice: 39.25,
    onHand: 0,
    forecast: 45,
    category: 'Shoes',
    status: 'out-of-stock',
    supplier: 'Footwear Fashions',
    sku: 'SH-FLT-ND6',
    lastUpdated: '2025-03-17'
  },
  {
    id: '19',
    name: 'Pearl Earrings (White)',
    sellPrice: 89.99,
    costPrice: 44.25,
    onHand: 42,
    forecast: 60,
    category: 'Jewelry',
    status: 'in-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-EAR-PRL',
    lastUpdated: '2025-03-19'
  },
  {
    id: '20',
    name: 'Champagne (Premium)',
    sellPrice: 59.99,
    costPrice: 32.50,
    onHand: 32,
    forecast: 50,
    category: 'Wine & Spirits',
    status: 'in-stock',
    supplier: 'Grand Vineyards Ltd.',
    sku: 'WN-CHP-PRM',
    lastUpdated: '2025-03-12'
  },
  {
    id: '21',
    name: 'Scented Candle Set (3-piece)',
    sellPrice: 39.99,
    costPrice: 18.75,
    onHand: 95,
    forecast: 120,
    category: 'Home & Kitchen',
    status: 'in-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-CND-SCT',
    lastUpdated: '2025-03-20'
  },
  {
    id: '22',
    name: 'Cocktail Ring (Sapphire)',
    sellPrice: 229.99,
    costPrice: 115.25,
    onHand: 18,
    forecast: 25,
    category: 'Jewelry',
    status: 'low-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-RNG-SPH',
    lastUpdated: '2025-03-22'
  },
  {
    id: '23',
    name: 'Leather Ankle Boots (Black, Size 7)',
    sellPrice: 159.99,
    costPrice: 79.50,
    onHand: 22,
    forecast: 40,
    category: 'Shoes',
    status: 'low-stock',
    supplier: 'Footwear Fashions',
    sku: 'SH-ABT-BLK7',
    lastUpdated: '2025-03-14'
  },
  {
    id: '24',
    name: 'Cashmere Throw Blanket',
    sellPrice: 129.99,
    costPrice: 65.50,
    onHand: 0,
    forecast: 30,
    category: 'Home & Kitchen',
    status: 'out-of-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-BLK-CSH',
    lastUpdated: '2025-03-21'
  },
  {
    id: '25',
    name: 'Evening Clutch Bag (Silver)',
    sellPrice: 89.99,
    costPrice: 42.75,
    onHand: 38,
    forecast: 50,
    category: 'Fashion',
    status: 'in-stock',
    supplier: 'Elite Fashion House',
    sku: 'BG-CLT-SLV',
    lastUpdated: '2025-03-15'
  },
  {
    id: '26',
    name: 'Wedding Guest Dress (Blue)',
    sellPrice: 149.99,
    costPrice: 74.50,
    onHand: 25,
    forecast: 40,
    category: 'Fashion',
    status: 'low-stock',
    supplier: 'Elite Fashion House',
    sku: 'DR-WED-BLU',
    lastUpdated: '2025-03-23'
  },
  {
    id: '27',
    name: 'Luxury Bath Towel Set',
    sellPrice: 89.99,
    costPrice: 43.25,
    onHand: 56,
    forecast: 75,
    category: 'Home & Kitchen',
    status: 'in-stock',
    supplier: 'Home Essentials Co.',
    sku: 'HM-TWL-LUX',
    lastUpdated: '2025-03-18'
  },
  {
    id: '28',
    name: 'Designer Sunglasses',
    sellPrice: 179.99,
    costPrice: 89.50,
    onHand: 30,
    forecast: 50,
    category: 'Fashion',
    status: 'in-stock',
    supplier: 'Elite Fashion House',
    sku: 'AC-SUN-DSG',
    lastUpdated: '2025-03-19'
  },
  {
    id: '29',
    name: 'Diamond Tennis Bracelet',
    sellPrice: 599.99,
    costPrice: 320.25,
    onHand: 0,
    forecast: 15,
    category: 'Jewelry',
    status: 'out-of-stock',
    supplier: 'Luxe Jewelers',
    sku: 'JW-BRC-DIA',
    lastUpdated: '2025-03-24'
  },
  {
    id: '30',
    name: 'Premium Gin (Botanical)',
    sellPrice: 42.99,
    costPrice: 22.50,
    onHand: 68,
    forecast: 90,
    category: 'Wine & Spirits',
    status: 'in-stock',
    supplier: 'Grand Vineyards Ltd.',
    sku: 'WN-GIN-BOT',
    lastUpdated: '2025-03-20'
  }
];
