#!/usr/bin/env python3
"""
Batch Customer Import Script
"""

import time
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Customer data batch
customers = [
  {
    "customer_id": "CUS021898",
    "first_name": "Ryan",
    "last_name": "Caldwell",
    "email": "audrey66@example.org",
    "phone": "+1 776.664.1034x1637",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-09-14",
    "first_purchase_date": "2024-10-03",
    "city": "Jacksonville",
    "country": "US",
    "preferred_size": "S",
    "preferred_category": "Activewear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 2,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS009866",
    "first_name": "Mohamed",
    "last_name": "Moran",
    "email": "steven58@example.net",
    "phone": "+44 +441632960277",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-06-28",
    "first_purchase_date": "2024-07-23",
    "city": "Newcastle",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Activewear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS024445",
    "first_name": "Danielle",
    "last_name": "Villarreal",
    "email": "darren32@example.com",
    "phone": "+61 (07) 5339 6376",
    "type": "Consumer",
    "segment": "VIP",
    "registration_date": "2024-09-27",
    "first_purchase_date": "2024-10-15",
    "city": "Gold Coast",
    "country": "AU",
    "preferred_size": "M",
    "preferred_category": "Accessories",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 8,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS033137",
    "first_name": "Beth",
    "last_name": "Baldwin",
    "email": "cnelis@example.org",
    "phone": "+353 990-405-6936x914",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-28",
    "first_purchase_date": "2024-08-30",
    "city": "Waterford",
    "country": "IE",
    "preferred_size": "XS",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS032015",
    "first_name": "Ellie",
    "last_name": "Miskell",
    "email": "gcotter@example.com",
    "phone": "+353 +1-784-978-5609x6577",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-08-31",
    "first_purchase_date": "2024-09-19",
    "city": "Drogheda",
    "country": "IE",
    "preferred_size": "XXL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 8,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS020939",
    "first_name": "Austin",
    "last_name": "Gonzalez",
    "email": "rmoreno@example.com",
    "phone": "+1 001-738-810-5202x49940",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-09-11",
    "first_purchase_date": "2024-09-20",
    "city": "New York",
    "country": "US",
    "preferred_size": "L",
    "preferred_category": "Footwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS016190",
    "first_name": "Kim",
    "last_name": "Newman",
    "email": "holmesluke@example.org",
    "phone": "+44 +44(0)151 496 0961",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-05-14",
    "first_purchase_date": "2024-05-25",
    "city": "Exeter",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS014108",
    "first_name": "Martyn",
    "last_name": "Hughes",
    "email": "douglas21@example.com",
    "phone": "+44 +441134960046",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-05-12",
    "first_purchase_date": "2024-05-26",
    "city": "Cambridge",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS015832",
    "first_name": "Howard",
    "last_name": "Hunter",
    "email": "vjames@example.com",
    "phone": "+44 +441154960476",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2023-12-16",
    "first_purchase_date": "2023-12-27",
    "city": "Bath",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Accessories",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS022311",
    "first_name": "Robert",
    "last_name": "Mills",
    "email": "harrisjennifer@example.org",
    "phone": "+1 213.717.8325",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-13",
    "first_purchase_date": "2024-08-28",
    "city": "Los Angeles",
    "country": "US",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS012363",
    "first_name": "Wayne",
    "last_name": "Swift",
    "email": "grantwayne@example.com",
    "phone": "+44 01914960929",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-28",
    "first_purchase_date": "2024-09-04",
    "city": "Liverpool",
    "country": "UK",
    "preferred_size": "M",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS004377",
    "first_name": "Michael",
    "last_name": "Smith",
    "email": "oharris@example.net",
    "phone": "+44 (0116) 4960560",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-02-20",
    "first_purchase_date": "2024-03-04",
    "city": "Newcastle",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": true,
    "purchase_frequency": 2,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS020565",
    "first_name": "Andrea",
    "last_name": "Newman",
    "email": "joseph11@example.org",
    "phone": "+1 (721)221-1936x07309",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2023-12-17",
    "first_purchase_date": "2024-01-07",
    "city": "Houston",
    "country": "US",
    "preferred_size": "S",
    "preferred_category": "Footwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": true,
    "purchase_frequency": 3,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS026396",
    "first_name": "Tanya",
    "last_name": "Osborne",
    "email": "morenojacob@example.com",
    "phone": "+61 07 6131 1778",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-04-24",
    "first_purchase_date": "2024-04-24",
    "city": "Sydney",
    "country": "AU",
    "preferred_size": "M",
    "preferred_category": "Outerwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 4,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS001307",
    "first_name": "Christopher",
    "last_name": "Webster",
    "email": "egardner@example.org",
    "phone": "+44 0117 496 0318",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-02-09",
    "first_purchase_date": "2024-02-24",
    "city": "Leeds",
    "country": "UK",
    "preferred_size": "XS",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Store",
    "is_repeat_buyer": true,
    "purchase_frequency": 4,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS033076",
    "first_name": "Keely",
    "last_name": "Milligan",
    "email": "icomerford@example.com",
    "phone": "+353 594.429.3870",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-09-12",
    "first_purchase_date": "2024-10-11",
    "city": "Kilkenny",
    "country": "IE",
    "preferred_size": "S",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS028213",
    "first_name": "Michael",
    "last_name": "Reed",
    "email": "charles45@example.com",
    "phone": "+61 +61-411-304-302",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2023-12-15",
    "first_purchase_date": "2024-01-12",
    "city": "Perth",
    "country": "AU",
    "preferred_size": "XS",
    "preferred_category": "Footwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS029679",
    "first_name": "Michael",
    "last_name": "Huynh",
    "email": "montoyanicole@example.com",
    "phone": "+61 0467.434.085",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-02-14",
    "first_purchase_date": "2024-02-24",
    "city": "Central Coast",
    "country": "AU",
    "preferred_size": "L",
    "preferred_category": "Footwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS009706",
    "first_name": "Jake",
    "last_name": "Bray",
    "email": "justin45@example.net",
    "phone": "+44 +44131 4960368",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-01-03",
    "first_purchase_date": "2024-01-15",
    "city": "Liverpool",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Outerwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS009509",
    "first_name": "Jeremy",
    "last_name": "Morris",
    "email": "aaron85@example.com",
    "phone": "+44 +44113 496 0298",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-05-30",
    "first_purchase_date": "2024-06-19",
    "city": "Birmingham",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS003281",
    "first_name": "Fiona",
    "last_name": "Johnson",
    "email": "hwatson@example.net",
    "phone": "+44 020 74960514",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-06-02",
    "first_purchase_date": "2024-06-09",
    "city": "London",
    "country": "UK",
    "preferred_size": "XS",
    "preferred_category": "Accessories",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 5,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS030055",
    "first_name": "David",
    "last_name": "Alexander",
    "email": "jenniferruiz@example.net",
    "phone": "+61 (02)17805211",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-05-13",
    "first_purchase_date": "2024-05-24",
    "city": "Adelaide",
    "country": "AU",
    "preferred_size": "S",
    "preferred_category": "Activewear",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS024712",
    "first_name": "Valerie",
    "last_name": "West",
    "email": "savannah52@example.org",
    "phone": "+61 +61 415 439 181",
    "type": "Consumer",
    "segment": "VIP",
    "registration_date": "2024-04-13",
    "first_purchase_date": "2024-04-21",
    "city": "Melbourne",
    "country": "AU",
    "preferred_size": "XS",
    "preferred_category": "Footwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 9,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS034105",
    "first_name": "Daniel",
    "last_name": "McPartlon",
    "email": "cbeattie@example.net",
    "phone": "+353 001-326-289-1262",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2023-12-25",
    "first_purchase_date": "2024-01-23",
    "city": "Navan",
    "country": "IE",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS008703",
    "first_name": "Nicholas",
    "last_name": "Finch",
    "email": "qwhite@example.com",
    "phone": "+44 028 9018101",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-07-07",
    "first_purchase_date": "2024-07-22",
    "city": "London",
    "country": "UK",
    "preferred_size": "XXL",
    "preferred_category": "Accessories",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS031877",
    "first_name": "Manus",
    "last_name": "Finegan",
    "email": "jilldevenney@example.net",
    "phone": "+353 (495)764-7574x1495",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2023-12-30",
    "first_purchase_date": "2024-01-25",
    "city": "Limerick",
    "country": "IE",
    "preferred_size": "XS",
    "preferred_category": "Footwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 4,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS032457",
    "first_name": "Eoghan",
    "last_name": "O'Kane",
    "email": "amanda10@example.net",
    "phone": "+353 (654)440-0999x13799",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-05-12",
    "first_purchase_date": "2024-06-01",
    "city": "Navan",
    "country": "IE",
    "preferred_size": "M",
    "preferred_category": "Outerwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": true,
    "purchase_frequency": 4,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS016418",
    "first_name": "Lynn",
    "last_name": "Hill",
    "email": "jill44@example.net",
    "phone": "+44 +44113 4960980",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-09-11",
    "first_purchase_date": "2024-09-28",
    "city": "York",
    "country": "UK",
    "preferred_size": "M",
    "preferred_category": "Casual Wear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS033356",
    "first_name": "Bethan",
    "last_name": "McDowell",
    "email": "mollie89@example.com",
    "phone": "+353 362-304-7172",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-06-08",
    "first_purchase_date": "2024-06-19",
    "city": "Swords",
    "country": "IE",
    "preferred_size": "XXL",
    "preferred_category": "Footwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS003090",
    "first_name": "Gordon",
    "last_name": "Mistry",
    "email": "bwatson@example.net",
    "phone": "+44 +44161 4960910",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2023-12-02",
    "first_purchase_date": "2023-12-28",
    "city": "Glasgow",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Activewear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS019345",
    "first_name": "Diana",
    "last_name": "Hoffman",
    "email": "cheyennechapman@example.net",
    "phone": "+1 +1-614-498-2162x4825",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-09-21",
    "first_purchase_date": "2024-10-06",
    "city": "Jacksonville",
    "country": "US",
    "preferred_size": "XXL",
    "preferred_category": "Underwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": true,
    "purchase_frequency": 2,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS010603",
    "first_name": "Bethany",
    "last_name": "Carr",
    "email": "hbryan@example.net",
    "phone": "+44 01154960883",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-18",
    "first_purchase_date": "2024-08-21",
    "city": "Leeds",
    "country": "UK",
    "preferred_size": "XXL",
    "preferred_category": "Activewear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS020478",
    "first_name": "Diana",
    "last_name": "Vasquez",
    "email": "rojasamanda@example.net",
    "phone": "+1 (788)586-5467x23213",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-01-26",
    "first_purchase_date": "2024-02-11",
    "city": "San Antonio",
    "country": "US",
    "preferred_size": "S",
    "preferred_category": "Outerwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS000688",
    "first_name": "Gavin",
    "last_name": "White",
    "email": "gillianwelch@example.net",
    "phone": "+44 0117 4960127",
    "type": "Consumer",
    "segment": "VIP",
    "registration_date": "2024-03-09",
    "first_purchase_date": "2024-03-24",
    "city": "Newcastle",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 15,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS022130",
    "first_name": "Jessica",
    "last_name": "Campos",
    "email": "mendezkelly@example.net",
    "phone": "+1 463.508.8502x9573",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-28",
    "first_purchase_date": "2024-09-23",
    "city": "Indianapolis",
    "country": "US",
    "preferred_size": "L",
    "preferred_category": "Footwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS031272",
    "first_name": "Kenneth",
    "last_name": "Sparks",
    "email": "shannonlopez@example.net",
    "phone": "+61 +61 3 7245 1478",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-31",
    "first_purchase_date": "2024-09-05",
    "city": "Melbourne",
    "country": "AU",
    "preferred_size": "XXL",
    "preferred_category": "Accessories",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS013254",
    "first_name": "Marian",
    "last_name": "Sharp",
    "email": "taylorleonard@example.com",
    "phone": "+44 +441514960985",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2023-12-29",
    "first_purchase_date": "2024-01-14",
    "city": "Bristol",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Underwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS029044",
    "first_name": "Joshua",
    "last_name": "Winters",
    "email": "emmalane@example.net",
    "phone": "+61 0452-971-419",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-09-12",
    "first_purchase_date": "2024-10-07",
    "city": "Canberra",
    "country": "AU",
    "preferred_size": "XL",
    "preferred_category": "Accessories",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS021498",
    "first_name": "Katie",
    "last_name": "Villegas",
    "email": "guerreroelizabeth@example.org",
    "phone": "+1 (531)639-7579x79798",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-06-25",
    "first_purchase_date": "2024-06-26",
    "city": "San Diego",
    "country": "US",
    "preferred_size": "XL",
    "preferred_category": "Outerwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS001371",
    "first_name": "Lewis",
    "last_name": "Byrne",
    "email": "gemmajenkins@example.org",
    "phone": "+44 +44117 496 0194",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-03-20",
    "first_purchase_date": "2024-04-08",
    "city": "Exeter",
    "country": "UK",
    "preferred_size": "L",
    "preferred_category": "Accessories",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 8,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS008247",
    "first_name": "Linda",
    "last_name": "Hughes",
    "email": "leonardsharp@example.com",
    "phone": "+44 +44121 4960342",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-08-18",
    "first_purchase_date": "2024-09-05",
    "city": "Exeter",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Activewear",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 4,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS022560",
    "first_name": "Jessica",
    "last_name": "Hess",
    "email": "schwartzryan@example.org",
    "phone": "+1 5295776733",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-01-03",
    "first_purchase_date": "2024-01-05",
    "city": "Phoenix",
    "country": "US",
    "preferred_size": "XL",
    "preferred_category": "Footwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS011409",
    "first_name": "Kim",
    "last_name": "Allan",
    "email": "bhumphreys@example.net",
    "phone": "+44 0121 496 0391",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-07-01",
    "first_purchase_date": "2024-07-31",
    "city": "Birmingham",
    "country": "UK",
    "preferred_size": "S",
    "preferred_category": "Underwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 2,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS011421",
    "first_name": "Mandy",
    "last_name": "Lee",
    "email": "qmorris@example.com",
    "phone": "+44 +44(0)29 2018 0646",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-03-22",
    "first_purchase_date": "2024-04-05",
    "city": "Exeter",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Underwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS001351",
    "first_name": "Joyce",
    "last_name": "Murphy",
    "email": "scott98@example.com",
    "phone": "+44 (0161) 4960660",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-08-05",
    "first_purchase_date": "2024-08-25",
    "city": "Sheffield",
    "country": "UK",
    "preferred_size": "XL",
    "preferred_category": "Footwear",
    "preferred_channel": "Online",
    "is_repeat_buyer": true,
    "purchase_frequency": 8,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS016815",
    "first_name": "Barbara",
    "last_name": "Parker",
    "email": "williamsterry@example.net",
    "phone": "+44 +44(0)1154960662",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-08-18",
    "first_purchase_date": "2024-09-15",
    "city": "Canterbury",
    "country": "UK",
    "preferred_size": "XXL",
    "preferred_category": "Underwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS021856",
    "first_name": "Beth",
    "last_name": "Stewart",
    "email": "hreeves@example.org",
    "phone": "+1 635-280-1732x8986",
    "type": "Consumer",
    "segment": "One-Time",
    "registration_date": "2024-07-06",
    "first_purchase_date": "2024-07-30",
    "city": "Fort Worth",
    "country": "US",
    "preferred_size": "L",
    "preferred_category": "Accessories",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS004440",
    "first_name": "Rosie",
    "last_name": "Campbell",
    "email": "jane16@example.net",
    "phone": "+44 0161 4960946",
    "type": "Consumer",
    "segment": "Regular",
    "registration_date": "2024-05-25",
    "first_purchase_date": "2024-05-27",
    "city": "Newcastle",
    "country": "UK",
    "preferred_size": "L",
    "preferred_category": "Footwear",
    "preferred_channel": "Store",
    "is_repeat_buyer": false,
    "purchase_frequency": 1,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS018532",
    "first_name": "Joshua",
    "last_name": "Harmon",
    "email": "brittany99@example.org",
    "phone": "+1 636.437.7639x4129",
    "type": "Consumer",
    "segment": "Loyal",
    "registration_date": "2024-09-23",
    "first_purchase_date": "2024-10-21",
    "city": "Indianapolis",
    "country": "US",
    "preferred_size": "XL",
    "preferred_category": "Accessories",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 8,
    "payment_terms": "Immediate"
  },
  {
    "customer_id": "CUS000847",
    "first_name": "Alan",
    "last_name": "Powell",
    "email": "trussell@example.org",
    "phone": "+44 (0141) 496 0288",
    "type": "Consumer",
    "segment": "VIP",
    "registration_date": "2024-03-08",
    "first_purchase_date": "2024-04-04",
    "city": "London",
    "country": "UK",
    "preferred_size": "XXL",
    "preferred_category": "Underwear",
    "preferred_channel": "Mobile App",
    "is_repeat_buyer": true,
    "purchase_frequency": 11,
    "payment_terms": "Immediate"
  }
]

def import_customers():
    """Import customers using MCP tools"""
    
    logger.info(f"🎯 Starting import of {len(customers)} customers")
    
    imported = 0
    failed = 0
    
    for i, customer in enumerate(customers, 1):
        try:
            customer_data = {
                'name': f"{customer.get('first_name', '')} {customer.get('last_name', '')}".strip(),
                'email': customer.get('email', '').lower().strip(),
                'phone': customer.get('phone', ''),
                'customer_rank': 1,
                'is_company': customer.get('type', '').lower() == 'company',
                'street': customer.get('city', ''),
                'ref': customer.get('customer_id', ''),
            }
            
            # Map country
            country_code = customer.get('country', 'UK').upper()
            country_map = {'UK': 76, 'US': 235, 'AU': 13, 'IE': 105}
            if country_code in country_map:
                customer_data['country_id'] = country_map[country_code]
            
            # Remove empty values
            customer_data = {k: v for k, v in customer_data.items() if v not in [None, '', False, 0]}
            
            logger.info(f"📝 Customer {i}/{len(customers)}: {customer_data['name']} ({customer_data['email']})")
            
            # This would be called via MCP in the actual implementation
            # result = mcp__odoo_mcp__odoo_create(
            #     instance_id="source-gym-plus-coffee",
            #     model="res.partner", 
            #     values=customer_data
            # )
            
            imported += 1
            
            # Brief pause to avoid overwhelming the server
            if i % 10 == 0:
                time.sleep(1)
                logger.info(f"✅ Processed {i} customers so far...")
                
        except Exception as e:
            logger.error(f"❌ Failed to process customer {i}: {e}")
            failed += 1
            
    logger.info(f"🎉 Batch completed: {imported} imported, {failed} failed")
    return imported, failed

if __name__ == "__main__":
    import_customers()
